version: '3.1'
services:
  springboot:
    image: docker7686/maven-web-application-mamatha:VERSION
    restart: always
    ports:
    - 9090:8080
    networks:
    - mavenappbridge
networks:
  mavenappbridge:
